### ISSUE TITLE
Identify not working for this layer in CAMP staging

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#510]
http://128.31.22.46/layers/geonode:test40

**Comment by capooti** [comment]
Interesting. This is not connected to permissions as I see the GML coming out from GeoServer WFS. Must be something which let the client fail, I will look into it.

**Comment by capooti** [comment]
Fixed it.

**Comment by blewis** [comment]
Still not working if logged in at Lubin  http://128.31.22.46/maps/1669/view

**Comment by capooti** [comment]
I believe the problem is that when removing the "download layer" permissions to a given user, the identify tool will fail for this user (unless he is the owner), as the tool relies on WFS. What it could be done in such a case is to fall back on the GetFeatureInfo of WMS. What do you say? I need some hours to fix this.

**Comment by capooti** [comment]
this is done.
