### ISSUE TITLE
ECW GeoServer plugin is missing

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#84]
We need to install the ECW plugin in GeoServer as some layer is using it, like this one:
http://worldmap.harvard.edu/data/geonode:ams

I guess we need to update the ansible script too.

**Comment by capooti** [comment]
Oh did not now that is still not fixed.
Will look into it.

**Comment by blewis** [comment]
Oops no maybe it is fixed.  We just need to load a bunch of ECW layers to the system at some point.  I think we were going to have Dave do it.  Or perhaps that is done?


Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
I think @ingenieroariel did something, but we still have the problem. Will look into it.

**Comment by capooti** [comment]
as suggested here: http://docs.geoserver.org/2.3.0/user/data/raster/gdal.html?highlight=gdal

we need to install GDAL and set GDAL_DATA.
I looked in the old server, and I believe GDAL was installed from source (version 1.9.2) or from this package: gdal192-Ubuntu12-gcc4.6.3-x86_64.tar.gz  

I think our best option is to compile GDAL 1.9.2 on the server, and set GDAL_DATA to the right directory.
@ingenieroariel let me know if this is a viable approach for your ansible script as well.

**Comment by capooti** [comment]
on old server GDAL_DATA is set to /gdal1192/data, and this directory contains:

$ ls /gdal192/data/
compdcs.csv          esri_extra.wkt             GDALLogoBW.svg     nitf_spec.xml       projop_wparm.csv          s57objectclasses.csv     vertcs.csv
coordinate_axis.csv  esri_StatePlane_extra.wkt  GDALLogoColor.svg  nitf_spec.xsd       s57agencies.csv           s57objectclasses_iw.csv  vertcs.override.csv
cubewerx_extra.wkt   esri_Wisconsin_extra.wkt   GDALLogoGS.svg     pci_datum.txt       s57attributes_aml.csv     seed_2d.dgn
datum_shift.csv      gcs.csv                    geoccs.csv         pci_ellips.txt      s57attributes.csv         seed_3d.dgn
ecw_cs.wkt           gcs.override.csv           gt_datum.csv       pcs.csv             s57attributes_iw.csv      stateplane.csv
ellipsoid.csv        gdal_datum.csv             gt_ellips.csv      pcs.override.csv    s57expectedinput.csv      trailer.dxf
epsg.wkt             gdalicon.png               header.dxf         prime_meridian.csv  s57objectclasses_aml.csv  unit_of_measure.csv

**Comment by ingenieroariel** [comment]
Yes, this can be scripted out. But remember, we are managing the python side via ansible because it can be quickly destroyed / enabled.

The geoserver side we are treating as a backend service and not provisioning it via scripts.

**Comment by capooti** [comment]
ah true. So for now I just hack on the server?

**Comment by ingenieroariel** [comment]
yes, we will b doing regular snapshots on that one

**Comment by capooti** [comment]
I think we need to compile GDAL with ECW support according to this:
https://trac.osgeo.org/gdal/wiki/ECW

@mbertrand do you remember how you installed GDAL with ECW support on old server?
I found a gdal1.7.3-linux64-ecw-gcc43.tar.gz file on that server, and I was wondering if you have used it to compile. But then how you moved to current version (1.9.2)?
thanks

**Comment by capooti** [comment]
I found a gdal192-Ubuntu12-gcc4.6.3-x86_64.tar.gz that contains gdalinfo and (I think) the GDAL java bindings, do we need that as well?

**Comment by capooti** [comment]
support enabled.
It is not working for the original layer in the ticket (not sure why), but here is another layer with a ecw store, and works well: http://worldmap.harvard.edu/data/geonode:1821east

**Comment by capooti** [comment]
Here are my notes on the (convoluted) procedure to enable ECW support in GS in case we need to replicate it at some point.
https://github.com/cga-harvard/cga-worldmap/wiki/How-to-enable-ECW-support-in-GeoServer

**Comment by capooti** [comment]
I have to reopen, as gdalinfo throws the same error discussed here:
http://osgeo-org.1560.x6.nabble.com/ECW-support-on-Fedora-Linux-error-td4991388.html
checking into this.

**Comment by capooti** [comment]
After recompiling libecwj now works. I think for some reasons some of the patch were not applied.
